# Read-only Home Assistant MQTT discovery + poll list for local Vitodens observation.
# No command_topic, no /set controls, no writable Home Assistant entities in this phase.

poll_list = {
    "device": {
        "identifiers": ["vitodens_300w_b3hb_local"],
        "name": "Vitodens 300-W Lokal",
        "model": "Vitodens 300-W B3HB",
        "manufacturer": "Viessmann",
    },
    "discovery_prefix": "homeassistant",
    "node_id": "vitodens",
    "dp_prefix": "vitodens_",
    "poll_interval": 10,
    "poll_groups": {
        "ONCEONLY": 0,
        "ALWAYS": 1,
        "OFTEN": 3,
        "SOMETIMES": 12,
        "RARELY": 60,
        "DEBUG": -1,
    },
    "mqtt_delay": 0.2,
    "beautifier": {
        "search": ["aussen", "speicher", "stoer", "rueck", "heiz", "warmwasser", "soll"],
        "replace": ["außen", "speicher", "stör", "rück", "heiz", "warmwasser", "soll"],
        "fixed": ["HK", "WW", "CPU"],
    },
    "domains": [
        {
            "domain": "sensor",
            "unit_of_measurement": "°C",
            "device_class": "temperature",
            "state_class": "measurement",
            "suggested_display_precision": 1,
            "poll": [
                ("OFTEN", "aussentemperatur", 0x0800, 2, 0.1, True),
                ("ALWAYS", "kesseltemperatur", 0x0802, 2, 0.1, False),
                ("OFTEN", "speichertemperatur", 0x0804, 2, 0.1, False),
                ("SOMETIMES", "abgastemperatur", 0x0808, 2, 0.1, False),
                ("OFTEN", "kesseltemperatur_soll", 0x555A, 2, 0.1, False),
                ("OFTEN", "speichertemperatur_soll_aktuell", 0x6500, 2, 0.1, False),
                ("SOMETIMES", "ruecklauftemperatur_berechnet", 0x0C20, 2, 0.01, False),
            ],
        },
        {
            "domain": "sensor",
            "state_class": "measurement",
            "suggested_display_precision": 0,
            "poll": [
                ("ALWAYS", "brenner_modulation", 0x55D3, 1, 1, False),
                ("OFTEN", "pumpenleistung", 0x0A3C, 1, 1, False),
                ("OFTEN", "volumenstrom", 0x0C24, 2, 1, False),
                ("OFTEN", "status", 0xA152, 2, 1, False),
                ("OFTEN", "betriebsart_2301_roh", 0x2301, 1, 1, True),
                ("OFTEN", "betriebsart_3323_roh", 0x3323, 1, 1, True),
                ("OFTEN", "m1_betriebsart_roh", 0x2323, 1, 1, False),
                ("OFTEN", "sparbetrieb_roh", 0x2302, 1, 1, True),
                ("OFTEN", "partybetrieb_roh", 0x2303, 1, 1, True),
                ("OFTEN", "m1_sparbetrieb_roh", 0x2331, 1, 1, False),
                ("OFTEN", "m1_partybetrieb_roh", 0x2330, 1, 1, False),
                ("SOMETIMES", "warmwasser_temperatur_soll", 0x6300, 1, 1, False),
                ("OFTEN", "speicherladepumpe", 0x6513, 1, 1, False),
                ("OFTEN", "zirkulationspumpe", 0x6515, 1, 1, False),
                ("OFTEN", "letzte_stoerung_roh", 0x7507, 9, "raw", False),
            ],
        },
        {
            "domain": "sensor",
            "icon": "mdi:calendar-clock",
            "poll": [
                ("RARELY", "systemzeit_heizung", 0x088E, 8, "vdatetime", False),
                ("RARELY", "hk1_zeitprogramm_montag", 0x2000, 8, "schedvdens", False),
                ("RARELY", "hk1_zeitprogramm_dienstag", 0x2008, 8, "schedvdens", False),
                ("RARELY", "hk1_zeitprogramm_mittwoch", 0x2010, 8, "schedvdens", False),
                ("RARELY", "hk1_zeitprogramm_donnerstag", 0x2018, 8, "schedvdens", False),
                ("RARELY", "hk1_zeitprogramm_freitag", 0x2020, 8, "schedvdens", False),
                ("RARELY", "hk1_zeitprogramm_samstag", 0x2028, 8, "schedvdens", False),
                ("RARELY", "hk1_zeitprogramm_sonntag", 0x2030, 8, "schedvdens", False),
                ("RARELY", "ww_zeitprogramm_montag", 0x2100, 8, "schedvdens", False),
                ("RARELY", "ww_zeitprogramm_dienstag", 0x2108, 8, "schedvdens", False),
                ("RARELY", "ww_zeitprogramm_mittwoch", 0x2110, 8, "schedvdens", False),
                ("RARELY", "ww_zeitprogramm_donnerstag", 0x2118, 8, "schedvdens", False),
                ("RARELY", "ww_zeitprogramm_freitag", 0x2120, 8, "schedvdens", False),
                ("RARELY", "ww_zeitprogramm_samstag", 0x2128, 8, "schedvdens", False),
                ("RARELY", "ww_zeitprogramm_sonntag", 0x2130, 8, "schedvdens", False),
                ("RARELY", "zirkulation_zeitprogramm_montag", 0x2200, 8, "schedvdens", False),
                ("RARELY", "zirkulation_zeitprogramm_dienstag", 0x2208, 8, "schedvdens", False),
                ("RARELY", "zirkulation_zeitprogramm_mittwoch", 0x2210, 8, "schedvdens", False),
                ("RARELY", "zirkulation_zeitprogramm_donnerstag", 0x2218, 8, "schedvdens", False),
                ("RARELY", "zirkulation_zeitprogramm_freitag", 0x2220, 8, "schedvdens", False),
                ("RARELY", "zirkulation_zeitprogramm_samstag", 0x2228, 8, "schedvdens", False),
                ("RARELY", "zirkulation_zeitprogramm_sonntag", 0x2230, 8, "schedvdens", False),
            ],
        },
        {
            "domain": "sensor",
            "unit_of_measurement": "°C",
            "device_class": "temperature",
            "state_class": "measurement",
            "suggested_display_precision": 0,
            "poll": [
                ("OFTEN", "hk1_normaltemperatur_soll", 0x2306, 1, 1, False),
                ("OFTEN", "hk1_reduzierte_temperatur_soll", 0x2307, 1, 1, False),
                ("OFTEN", "hk1_komforttemperatur_soll", 0x2308, 1, 1, False),
            ],
        },
        {
            "domain": "sensor",
            "state_class": "measurement",
            "suggested_display_precision": 1,
            "poll": [
                ("SOMETIMES", "hk1_heizkurve_neigung", 0x27D3, 1, 0.1, False),
            ],
        },
        {
            "domain": "sensor",
            "state_class": "measurement",
            "suggested_display_precision": 0,
            "poll": [
                ("SOMETIMES", "hk1_heizkurve_niveau", 0x27D4, 1, 1, True),
            ],
        },
        {
            "domain": "sensor",
            "state_class": "total_increasing",
            "suggested_display_precision": 0,
            "poll": [
                ("RARELY", "brennerstarts", 0x088A, 4, 1, False),
            ],
        },
        {
            "domain": "sensor",
            "unit_of_measurement": "h",
            "device_class": "duration",
            "state_class": "total_increasing",
            "suggested_display_precision": 1,
            "poll": [
                ("RARELY", "brennerbetriebsstunden", 0x08A7, 4, 2.7777778e-4, False),
            ],
        },
        {
            "domain": "binary_sensor",
            "payload_on": "1",
            "payload_off": "0",
            "poll": [
                ("OFTEN", "brennerstoerung", 0x0884, 1, 1, False),
                ("OFTEN", "eingang_stb_stoerung", 0x0A82, 1, 1, False),
                ("OFTEN", "fehlerstatus_brennersteuergeraet", 0x5738, 1, 1, False),
            ],
        },
    ],
}
